### ISSUE TITLE
Is there an ext for visual studio code

### ISSUE THREAD

**Issue by quytangvn** [league1991/CodeAtlasVsix#3]
I use visual studio code for development.
I find your plugin is awesome for viewing dependencies graph.
My questions are:
- Do you support plug in for vscode?
- If no, do you know any ext work similar in vscode?

Thank you very much!

**Comment by league1991** [comment]
@quytangvn  VSCode won't be supported, because the API is totally different and I don't have enough time the write the plugin from scratch. Instead, Visual Studio Community is supported, you can try it if it's possible.
