### ISSUE TITLE
shortcut key is invalid some like "Alt+F"

### ISSUE THREAD

**Issue by pedoc** [league1991/CodeAtlasVsix#5]
may be the interaction between plugins, such as R#,so,recommended integration context menu item to add an analysis item

**Comment by league1991** [comment]
I will consider that. You can also add items by pressing the green "+" icon in CodeGraph toolbar.

**Comment by solwhitecobalt** [comment]
Ctrl+Num and Alt+Num is not working either. Assuming Num is the Num Lock button.

**Comment by league1991** [comment]
Num is 1/2/3/4/5 key

solwhitecobalt <notifications@github.com> 于2020年9月19日周六 下午7:30写道：
